### ISSUE TITLE
Menu 采用非驼峰标签语法无法显示图标

### ISSUE THREAD

**Issue by namecho** [element-plus/element-plus-icons#13]
![image](https://user-images.githubusercontent.com/49669810/129655770-c337c090-ce15-4d3c-962f-4a7749428225.png)

**Comment by JeremyWuuuuu** [comment]
奇怪，可以不用 setup sugar 试试吗？官网应该都是好的。

**Comment by namecho** [comment]
一样的，也不行，其他图标都可以正常显示，唯独 menu 不行

**Comment by JeremyWuuuuu** [comment]
> 一样的，也不行，其他图标都可以正常显示，唯独 menu 不行

我来看看到底什么原因

**Comment by JeremyWuuuuu** [comment]
> 一样的，也不行，其他图标都可以正常显示，唯独 menu 不行

大概知道什么原因了，https://developer.mozilla.org/en-US/docs/Web/HTML/Element/menu 因为 HTML 自带了 menu 标签，
可以这样用：

```ts
import { Menu as MenuIcon } from '@element-plus/icons`
```

**Comment by namecho** [comment]
好的

**Comment by JeremyWuuuuu** [comment]
> 好的
解决了么？如果解决了就可以 close 掉了
