### ISSUE TITLE
How to add svg icon globally [Question]

### ISSUE THREAD

**Issue by adiramardiani** [element-plus/element-plus-icons#17]
Hai @JeremyWuuuuu 
Currently I'm upgrading from element plus 1.1.0-beta.24 to 1.2.0-beta.3

I because now all icon use svg icon, I have some breaking change 

I have some button on my page like this (*of course the button on the template and import on the script tag*)
```vue
<el-button icon="el-icon-plus">Create</el-button>
```

and after upgrading the structure will be like this
```vue
<el-button :icon="Plus">Create</el-button>

import { Plus } from '@element-plus/icons'
```

For one page this is worth it, but for upgrading hundred page is very hard

My idea is use global component, so we not import on every page, and for icon="el-icon-plus" I can replace on vs code with :icon="Plus"
I try to use it on global component but not working
```js
import { Plus } from '@element-plus/icons'
export default function (app) {
    app.component(Plus)
}

```

Can you help me

**Comment by skalidindi** [comment]
Would love an answer to this as well.

**Comment by JeremyWuuuuu** [comment]
Hi, you can do the global registration for the icon component, then pass the component **name** as **string** into the icon prop, something like: 

> app.ts

```ts
import { SomeIcon } from "some-lib"

app.component(SomeIcon)
```

> component.bye


```vue
<template>
  <el-button icon="SomeIcon" />
</template>

```
Then `el-icon` will use `Vue.resolveCompnent` to resolve the component. 

I believe this will work. 

Let me know if you have any questions.

**Comment by julienripet** [comment]
@JeremyWuuuuu Is there any way to globally register all the icons at once? Thanks in advance

**Comment by JeremyWuuuuu** [comment]
Oh you can just do this: 


```js
import * as AllIcons from "@element-plus/icons"


Object.entries(AllIcons).map(([iconName, icon) => {
  app.component(iconName, icon)
})

```

I believe this will do the trick 

But I doubt that this is worth it since if you do that the bundle size would be much larger than it was, you can always pick the icons you want to use and register them globally. 


cc @sxzz I believe we can use some vite plugin to solve this manual import issue.

**Comment by sxzz** [comment]
I am working on it.

**Comment by sxzz** [comment]
🎉 The best practices of Element Plus Icons is here.
https://github.com/sxzz/element-plus-best-practices/blob/93be0126da935109ae25cf2f9539991fb4f1d87c/vite.config.ts#L38
