### ISSUE TITLE
是否可以cdn方式直接引用？如果可以的话可否说明一下？

### ISSUE THREAD

**Issue by changly** [element-plus/element-plus-icons#20]
目前采用的方式没有通过npm，单个为vue文件引入是没问题的，是否可以直接cdn引入呢？

**Comment by sxzz** [comment]
目前暂不支持，将在近期完善。

**Comment by changly** [comment]
> 目前暂不支持，将在近期完善。

好的 期待更快的支持😊

**Comment by sxzz** [comment]
https://codepen.io/sxzz/pen/GRMgavo
