### ISSUE TITLE
在vite中怎么配合unplugin-icons做按需加载？或者是推荐哪个按需加载方式

### ISSUE THREAD

**Issue by qc-z** [element-plus/element-plus-icons#22]
[unplugin-icons](https://github.com/antfu/unplugin-icons)

**Comment by sxzz** [comment]
icon 的最佳实践还在探索中...
相信在近期就能给出一个解决方案

**Comment by shinglove** [comment]
@sxzz 在iconify 上看到有element-plus的图标集合 但在模版里面写<i-ep-aim />  components.d.ts 下面没有自动引入组件 是这个原因吗

**Comment by sxzz** [comment]
icon 并不会被自动导入。

**Comment by sxzz** [comment]
Please refer to Please refer to https://github.com/sxzz/element-plus-best-practices/blob/93be0126da935109ae25cf2f9539991fb4f1d87c/vite.config.ts#L38
