### ISSUE TITLE
@element-plus/icons has been deprecated ?

### ISSUE THREAD

**Issue by pdsuwwz** [element-plus/element-plus-icons#24]
https://www.npmjs.com/package/@element-plus/icons

![image](https://user-images.githubusercontent.com/19891724/144977224-cc0de4be-723f-4b66-a311-299313422c58.png)

**Comment by sxzz** [comment]
Yes. Please use `@element-plus/icons-vue`

**Comment by pdsuwwz** [comment]
> Yes. Please use `@element-plus/icons-vue`

`@element-plus/icons-vue` works for me, thanks!
