### ISSUE TITLE
npm 提示：This package has been deprecated

### ISSUE THREAD

**Issue by Jamie-Yang** [element-plus/element-plus-icons#26]
还有一个问题，npmjs.com 最后一个版本是 v0.0.11，但是 Releases 里已经有 v0.2.4 了

**Comment by kailong321200875** [comment]
@element-plus/icons 之前的包官方已经废弃了，现在变成这个包了。@element-plus/icons-svg

**Comment by Jamie-Yang** [comment]
> @element-plus/icons 之前的包官方已经废弃了，现在变成这个包了。@element-plus/icons-svg

谢了，按你说的找了下，应该是变成了 @element-plus/icons-vue。@element-plus/icons-svg 是纯 SVG 资源包
