### ISSUE TITLE
The Element CSS style does not work properly

### ISSUE THREAD

**Issue by qsyj0522** [element-plus/element-plus-icons#29]
This is my code, rendering a close icon.  However, attributes cannot be inherited correctly .
`
  <el-icon :size="10" color="blue">
    <ElIconClose />
  </el-icon>
`
![image](https://user-images.githubusercontent.com/58837225/148003055-a6c678d9-fc8c-4892-b2d0-2c0e9ca6c00e.png)

If I change it to the following it will work fine.

![image](https://user-images.githubusercontent.com/58837225/148002800-ea56a4f5-518a-4774-abcf-de0286490a78.png)

![image](https://user-images.githubusercontent.com/58837225/148002956-2d1d13b9-9c69-4bbb-9f08-a47dc5b4ab3e.png)

**Comment by sxzz** [comment]
This issue seems to be fixed. If the problem consists, please go to [main repo](https://github.com/element-plus/element-plus) and create a new issue.
