### ISSUE TITLE
package.json types 文件路径错误

### ISSUE THREAD

**Issue by mioxs** [element-plus/element-plus-icons#56]
![image](https://user-images.githubusercontent.com/49021590/203086588-f94efc15-206b-4c66-92da-3feb078a10c8.png)

无法识别到types路径
![image](https://user-images.githubusercontent.com/49021590/203089675-43352927-fffd-4a24-8da2-47b1ca2ff193.png)

**Comment by k713927** [comment]
为啥这个 issue突然关闭了呢，我也遇到同样的问题

**Comment by ilovesusu** [comment]
@mioxs 这个你怎么解决了？

**Comment by mioxs** [comment]
> @mioxs 这个你怎么解决了？

查看pr提交的内容
