### ISSUE TITLE
Cannot find name 'IconEp**'.

### ISSUE THREAD

**Issue by busyhe** [element-plus/element-plus-icons#68]
按需引入这种错误如何解决
![Xnip2024-03-31_19-58-11](https://github.com/element-plus/element-plus-icons/assets/17348825/09383b23-2736-479c-bc1b-56d6a6ccf2b5)

**Comment by sxzz** [comment]
Please look for the docs of plugin you're using, like [unplugin-icons](https://github.com/antfu/unplugin-icons), [unplugin-auto-import](https://github.com/antfu/unplugin-auto-import), [UnoCSS](https://unocss.dev/)
